#! /bin/bash

clear

cp ./src/.bashrc $HOME
cp ./src/.bash_aliases $HOME
cp ./src/.dircolors $HOME
cp ./src/.vimrc $HOME
cp -r ./src/.vim $HOME

source $HOME/.profile

echo "Home Directory Listing"
ls -lah --color $HOME