#! /bin/bash

clear

echo "Installing JibSales bash profile"
echo

cp ./src/.bashrc $HOME
cp ./src/.bash_aliases $HOME
cp ./src/.dircolors $HOME
cp ./src/.vimrc $HOME
cp -r ./src/.vim $HOME

echo
echo "Finished installing."
echo

ls -lah --color $HOME