#! /usr/bin/env bash

# Templates
REVIEW_DSC_FILE="/Users/srquinn/Documents/templates/post_review/description.txt"
REVIEW_TST_FILE="/Users/srquinn/Documents/templates/post_review/testing-done.txt"
REVIEW_MAIN_GROUPS="sl-fabric-dev"

# Hosts
SSH_HOST_ALIAS="devbox"

# Files and Directories
WIDGETS_LOCAL="/Users/srquinn/Projects/Widgets"
WIDGETS_REMOTE="/home/srquinn/Projects/Widgets"

VOODOO_LOCAL="/Users/srquinn/Projects/Voodoo"
VOODOO_REMOTE="/home/srquinn/Projects/Voodoo"

TETRIS_LOCAL="${WIDGETS_LOCAL}/src/SoftlinesTetrisAssets"
TETRIS_REMOTE="${WIDGETS_REMOTE}/src/SoftlinesTetrisAssets"

TESTS_LOCAL="/Users/srquinn/Projects/AutomatedTests"
TESTS_REMOTE="/home/srquinn/Projects/Tests"

# Binary shortcuts
brazil="/apollo/env/SDETools/bin/brazil-build"

# Code Review
review(){
  case $2 in
    "widgets")
	  packages='-t SoftlinesTechWidgets -t SoftlinesTetrisAssets -t SoftlinesTechWidgetComponents'
	;;
    "voodoo")
      packages='-t SoftlinesVoodoo -t SoftlinesTechWidgetComponents'
    ;;
    "tests")
      packages='-t SoftlinesAutomatedTests'
    ;;
  esac;

  case $3 in
    "new")
      post-review \
        --no-review-guess \
        --description-file $REVIEW_DSC_FILE \
        --testing-done-file $REVIEW_TST_FILE \
        --target-groups=$REVIEW_MAIN_GROUPS \
        --parent ${4-mainline} \
        $packages
    ;; 
    "update")
      post-review \
        --review-request-id=$4 \
        --parent ${5-mainline} \
        $packages 
    ;;
    *)
      echo ""
      echo -e "review has the following options:"
      echo -e "  review <workspace> new <parent>"
      echo -e "  review <workspace> update <id> <parent>"
      echo ""
    ;;
  esac;
}

# Work with the logs on desktop
logs(){
  # Map the apollo environment alias to the hack api
  case $3 in
    "widgets")
      apollo_env_alias="HorizontePlatform"
    ;;
    "voodoo")
      apollo_env_alias="SoftlinesVoodoo"
    ;;
  esac;

  # Process the logging command
  case $2 in
    "list")
      ssh $SSH_HOST_ALIAS -t "ls -lrt --color=auto /apollo/env/${apollo_env_alias}/var/output/logs"
    ;;
    "tail")
      ssh $SSH_HOST_ALIAS -t "cd /apollo/env/${apollo_env_alias}/var/output/logs ; tail -f $4 | tr '|' '\n'"
    ;;
    *)
      echo ""
      echo -e "logs has the following options:"
      echo -e "  log list stw|voodoo"
      echo -e "  log tail stw|voodoo <log_name>"
    ;;
  esac;
}

# Sync files with devbox
sync(){
  case $2 in
    "widgets")
      echo -e "Syncing STW Workspace"
      rsync -av $WIDGETS_LOCAL/src/ $SSH_HOST_ALIAS:$WIDGETS_REMOTE/src
      
      echo -e "Updating STW Assets on $SSH_HOST_ALIAS"
      # Handle uploading JSP views
      views_dir="SoftlinesTechWidgets/webapps/HorizonteWebApp/WEB-INF/views"
      rsync -av $WIDGETS_LOCAL/src/$views_dir/ $SSH_HOST_ALIAS:$WIDGETS_REMOTE/apollo-overrides/$views_dir
    ;;

    "voodoo")
      echo -e "Syncing Voodoo Workspace with ${SSH_HOST_ALIAS}"
      rsync -av $VOODOO_LOCAL/src/ $SSH_HOST_ALIAS:$VOODOO_REMOTE/src
            
      echo -e "Updating Voodoo Assets on ${SSH_HOST_ALIAS}"
      # Handle uploading JSP views
      webapps_dir="SoftlinesVoodoo/webapps"
      local_views_dir="${VOODOO_LOCAL}/src/${webapps_dir}/WEB-INF/views"
      remote_views_dir="$VOODOO_REMOTE}/apollo-overrides/${webapps_dir}/ROOT/WEB-INF/views"
      rsync -av $local_views_dir/ $SSH_HOST_ALIAS:$remote_views_dir
      
      # Handle uploading all static assets
      local_target_dir="${VOODOO_LOCAL}/src/${webapps_dir}/target"
      remote_target_dir="${VOODOO_REMOTE}/apollo-overrides/${webapps_dir}/target"
      rsync -av $local_target_dir/ $SSH_HOST_ALIAS:$remote_target_dir
    ;;

    "tests")
      echo -e "Syncing Automated Tests Workspace"
      rsync -av $TESTS_LOCAL/src/ $SSH_HOST_ALIAS:$TESTS_REMOTE/src
    ;;
  esac;
}

# Remote control for the AUI Dev Server
aui(){
  case $2 in
    "tetris")
      echo -e "\nStarting Tetris Assets build watcher..."
      ssh $SSH_HOST_ALIAS -t "cd ${TETRIS_REMOTE} ; ${brazil} guard"
    ;;
  esac;
}

# Replace web.xml with development config and restart tomcat
restart(){
  case $2 in
    "widgets")
      remote_web_xml="${WIDGETS_REMOTE}/apollo-overrides/SoftlinesTechWidgets/webapps/HorizonteWebApp/WEB-INF/web.xml"
      echo -e '\nRestarting Widgets with development config...'
      ssh $SSH_HOST_ALIAS -t "rm ${remote_web_xml} ;\
                     ln -s ~/config/tomcat/widgets-web.xml ${remote_web_xml} ;\
                     sudo sudo -u nobody nohup /apollo/bin/env /apollo/env/HorizontePlatform/bin/forceTomcatRestart > /dev/null 2>&1 ;"
      echo -e '... [DONE]\n'
    ;;
    "voodoo")
      ssh $SSH_HOST_ALIAS -t "echo -e '\nRestarting Voodoo with development config...' ;\
                     rm ${VOODOO_REMOTE}/WEB-INF/web.xml ;\
                     ln -s ~/config/tomcat/voodoo-web.xml ${VOODOO_REMOTE}/WEB-INF/web.xml ;\
                     sudo sudo -u nobody nohup /apollo/bin/env /apollo/env/SoftlinesVoodoo/ApolloCmd/Activate/500StartTomcat > /dev/null 2>&1 ;\
                     echo -e '... [DONE]\n'"
    ;;
  esac;
}

# Quickly convert a markdown file and add to paste board
wiki(){
  pandoc -f markdown -t mediawiki "./$2" | pbcopy
}

# Command Parsing
case $1 in
  
  "review") review "$@" ;;
  "sync") sync "$@" ;;
  "restart") restart "$@" ;;
  "logs") logs "$@" ;;
  "aui") aui "$@" ;; 
  "wiki") wiki "$@" ;;

  *)
    echo ""
    echo -e "hack makes life suck less:"
    echo -e "  hack review <type>    code review management"
    echo -e "  hack sync <target>    sync local files with devbox"
    echo -e "  hack restart <env>    restart tomcat with development config"
    echo ""
  ;;

esac;
