# Only display the context when we're not ourselves
export DEFAULT_USER=$USER

# Give things some space
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

# Style vi-mode
POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='blue'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='white'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='yellow'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='white'

# Set the segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context time aws dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs nvm vi_mode)

prompt powerlevel9k
