# load zgen
source "${HOME}/.zgen/zgen.zsh"

# custom plugins
for module in ${HOME}/.dotfiles/zsh/modules/*.zsh; do
  source $module
done

# if the init scipt doesn't exist
if ! zgen saved; then
  source "${HOME}/.dotfiles/zsh/loader.zsh"
fi
