# load zgen
source "${HOME}/.zgen/zgen.zsh"

path=(
  $HOME/bin
  $HOME/.dotfiles/bin
  $HOME/.dotfiles-local/bin
  $path
)

export DOTFILES=$HOME/.dotfiles
export DOTFILES_LOCAL=$HOME/.dotfiles-local

# if the init scipt doesn't exist
if ! zgen saved; then
  source "${DOTFILES}/zsh/loader.zsh"
fi

# Source the local stuff
for module in $DOTFILES/zsh/modules/*.zsh; do
  source $module
done

if [ -d $DOTFILES_LOCAL/zsh ]; then
  for module in $DOTFILES_LOCAL/zsh/*.zsh; do
    source $module
  done
fi
